In [30]:
from sklearn import datasets
import matplotlib.pyplot as plt
import numpy as np

In [31]:
iris = datasets.load_iris()
digits = datasets.load_digits()
iris_X = iris.data
iris_y = iris.target
np.unique(iris_y)

array([0, 1, 2])

In [50]:
# Split iris data in train and test data
# A random permutation, to split the data randomly
np.random.seed(8)
indices = np.random.permutation(len(iris_X))
# print(indices)
# print(indices[-10:])
# print(indices[:-10])
iris_X_train = iris_X[indices[:-10]]
iris_y_train = iris_y[indices[:-10]]
iris_X_test = iris_X[indices[-10:]]
iris_y_test = iris_y[indices[-10:]]

In [54]:
# Create and fit a nearest-neighbor classifier
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(iris_X_train,iris_y_train)
knn.predict(iris_X_test)

array([1, 1, 2, 0, 2, 2, 2, 2, 2, 1])

In [55]:
iris_y_test

array([1, 1, 2, 0, 2, 1, 2, 2, 2, 1])