## 数据操作

In [1]:
from mxnet import nd

In [6]:
x=nd.arange(12)
x


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
<NDArray 12 @cpu(0)>

In [3]:
x.shape

(12,)

In [4]:
x.size

12

In [7]:
X=x.reshape(3,4)

In [9]:
nd.zeros((2,3,4))


[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
<NDArray 2x3x4 @cpu(0)>

In [10]:
nd.ones((3,4))


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<NDArray 3x4 @cpu(0)>

In [14]:
# 我们也可以通过Python的列表（list）指定需要创建的NDArray中每个元素的值
Y = nd.array([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

In [13]:
# 有些情况下，我们需要随机⽣成NDArray中每个元素的值。下⾯我们创建⼀个形状为(3,
# 4)的NDArray。它的每个元素都随机采样于均值为0、标准差为1的正态分布
nd.random.normal(0,1,(3,4))


[[ 1.1630785   0.4838046   0.29956347  0.15302546]
 [-1.1688148   1.558071   -0.5459446  -2.3556297 ]
 [ 0.54144025  2.6785064   1.2546344  -0.54877406]]
<NDArray 3x4 @cpu(0)>

In [15]:
X+Y


[[ 2.  2.  6.  6.]
 [ 5.  7.  9. 11.]
 [12. 12. 12. 12.]]
<NDArray 3x4 @cpu(0)>

In [16]:
X*Y


[[ 0.  1.  8.  9.]
 [ 4. 10. 18. 28.]
 [32. 27. 20. 11.]]
<NDArray 3x4 @cpu(0)>

In [17]:
X/Y


[[ 0.    1.    0.5   1.  ]
 [ 4.    2.5   2.    1.75]
 [ 2.    3.    5.   11.  ]]
<NDArray 3x4 @cpu(0)>

In [19]:
Y.exp()

MXNetError: [09:40:29] c:\jenkins\workspace\mxnet-tag\mxnet\src\operator\tensor\./dot-inl.h:1240: Check failed: L[!Ta].Size() == R[Tb].Size() (4 vs. 3) : dot shape error: [3,4] X [3,4]

In [22]:
nd.dot(X,Y.T)


[[ 18.  20.  10.]
 [ 58.  60.  50.]
 [ 98. 100.  90.]]
<NDArray 3x3 @cpu(0)>

In [23]:
nd.concatenate([X,Y],0)


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [ 2.  1.  4.  3.]
 [ 1.  2.  3.  4.]
 [ 4.  3.  2.  1.]]
<NDArray 6x4 @cpu(0)>

In [24]:
nd.concatenate([X,Y], 1)


[[ 0.  1.  2.  3.  2.  1.  4.  3.]
 [ 4.  5.  6.  7.  1.  2.  3.  4.]
 [ 8.  9. 10. 11.  4.  3.  2.  1.]]
<NDArray 3x8 @cpu(0)>

使⽤条件判断式可以得到元素为0或1的新的NDArray。以`X == Y`为例，如果X和Y在相同位置的
条件判断为真（值相等），那么新的NDArray在相同位置的值为1；反之为0

In [25]:
X == Y


[[0. 1. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<NDArray 3x4 @cpu(0)>

In [30]:
X.sum()


[66.]
<NDArray 1 @cpu(0)>

可以通过`asscalar`函数将结果变换为Python中的标量。下⾯例⼦中$X$的$L_2$范数结果同上例⼀样是单元素NDArray，
但最后结果变换成了Python中的标量;也可以把Y.exp()、 X.sum()、 X.norm()等分别改写为nd.exp(Y)、 nd.sum(X)、 nd.norm(X)等

In [31]:
X.norm().asscalar()

22.494442

### ⼴播机制
当对两个形状不同的NDArray按元素运算时，可能会触发⼴播（broadcasting）机制：
先适当复制元素使这两个NDArray形状相同后再按元素运算

由于A和B分别是3⾏1列和1⾏2列的矩阵，如果要计算A + B，那么A中第⼀列的3个元素被⼴播
（复制）到了第⼆列，而B中第⼀⾏的2个元素被⼴播（复制）到了第⼆⾏和第三⾏。如此，就可以
对2个3⾏2列的矩阵按元素相加。

In [32]:
A = nd.arange(3).reshape((3, 1))
B = nd.arange(2).reshape((1, 2))
A,B

(
 [[0.]
  [1.]
  [2.]]
 <NDArray 3x1 @cpu(0)>, 
 [[0. 1.]]
 <NDArray 1x2 @cpu(0)>)

In [33]:
A + B


[[0. 1.]
 [1. 2.]
 [2. 3.]]
<NDArray 3x2 @cpu(0)>

### 索引
在NDArray中，索引（index）代表了元素的位置。 NDArray的索引从0开始逐⼀递增。例如，⼀
个3⾏2列的矩阵的⾏索引分别为0、 1和2，列索引分别为0和1。
在下⾯的例⼦中，我们指定了NDArray的⾏索引截取范围[1:3]。依据左闭右开指定范围的惯例，
它截取了矩阵X中⾏索引为1和2的两⾏

In [34]:
X[1:3]


[[ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 2x4 @cpu(0)>

In [36]:
X[1,2]=9
X


[[ 0.  1.  2.  3.]
 [ 4.  5.  9.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

当然，我们也可以截取⼀部分元素，并为它们重新赋值。在下⾯的例⼦中，我们为⾏索引为1的每⼀列元素重新赋值

In [37]:
X[1:2,:] = 12
X


[[ 0.  1.  2.  3.]
 [12. 12. 12. 12.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

### 运算的内存开销
在前⾯的例⼦⾥我们对每个操作新开内存来存储运算结果。举个例⼦，即使像$Y = X + Y$这样
的运算，我们也会新开内存，然后将Y指向新内存。为了演⽰这⼀点，我们可以使⽤Python⾃带
的id函数：如果两个实例的ID⼀致，那么它们所对应的内存地址相同；反之则不同

In [38]:
before = id(Y)
Y = Y + X
id(Y) == before

False

如果想指定结果到特定内存，我们可以使⽤前⾯介绍的索引来进⾏替换操作。在下⾯的例⼦中，
我们先通过`zeros_like`创建和Y形状相同且元素为0的NDArray，记为Z。接下来，我们把X +
Y的结果通过[:]写进Z对应的内存中

In [41]:
Z = Y.zeros_like()
before = id(Z)
Z[:] = X + Y
before == id(Z)

True

实际上，上例中我们还是为$X + Y$开了临时内存来存储计算结果，再复制到Z对应的内存。如果
想避免这个临时内存开销，我们可以使⽤运算符全名函数中的out参数

In [42]:
nd.elemwise_add(X,Y,out=Z)
id(Z) == before

True

如果X的值在之后的程序中不会复⽤，我们也可以⽤ X[:] = X + Y 或者 X += Y 来减少运算
的内存开销。

In [43]:
before = id(X)
X += Y
id(X) == before

True

### NDArray和NumPy相互变换
我们可以通过`array`函数和`asnumpy`函数令数据在NDArray和NumPy格式之间相互变换

In [45]:
import numpy as np
P = np.ones((2,3))
D = nd.array(P)
D


[[1. 1. 1.]
 [1. 1. 1.]]
<NDArray 2x3 @cpu(0)>

In [46]:
D.asnumpy()

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)